### ISSUE TITLE
Support for D3 v4.4.0

### ISSUE THREAD

**Issue by RehanSaeed** [pablomolnar/radial-progress-chart#10]
Getting the following error with D3 4.4.0. Also the `round` option doesn't seem to work, I always get round corners to my circles instead of square ones.

```
TypeError: Cannot read property 'arc' of undefined
    at new i (http://localhost:8080/bower_components/radial-progress-chart/dist/radial-progress-chart.min.js:1:1526)
    at HTMLDivElement.eval (eval at globalEval (http://localhost:8080/bower_components/jquery/dist/jquery.js:343:5), <anonymous>:29:5)
    at Function.each (http://localhost:8080/bower_components/jquery/dist/jquery.js:365:19)
    at jQuery.fn.init.each (http://localhost:8080/bower_components/jquery/dist/jquery.js:137:17)
    at eval (eval at globalEval (http://localhost:8080/bower_components/jquery/dist/jquery.js:343:5), <anonymous>:2:29)
    at eval (<anonymous>)
    at Function.globalEval (http://localhost:8080/bower_components/jquery/dist/jquery.js:343:5)
    at domManip (http://localhost:8080/bower_components/jquery/dist/jquery.js:5291:15)
    at jQuery.fn.init.append (http://localhost:8080/bower_components/jquery/dist/jquery.js:5431:10)
    at jQuery.fn.init.<anonymous> (http://localhost:8080/bower_components/jquery/dist/jquery.js:5525:18)
```

**Comment by gankit** [comment]
I have the same issue!

**Comment by anvial** [comment]
Have the same issue. Is there a solution of this problem?

**Comment by robalvsan** [comment]
Use D3 3.5.0

https://github.com/d3/d3/releases/tag/v3.5.0
